name: Build APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: android-actions/setup-android@v2

      - run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: ChatAi-APK
          path: app/build/outputs/apk/release/*.apk
